#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

# PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=23 \
    padding_right=23 \
    notch_width=188 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xff24273a \
    label.drawing=no \
    script="$PLUGIN_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes

sketchybar --add item weather q \
    --set weather \
    icon=\
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:15.0" \
    update_freq=1800 \
    script="$PLUGIN_DIR/weather.sh" \
    --subscribe weather system_woke

sketchybar --add event aerospace_workspace_change

sketchybar --add item aerospace_workspace q \
    --set aerospace_workspace \
    icon=󰘳 \
    icon.color=0xff91d7e3 \
    label.padding_left=2 \
    script="$PLUGIN_DIR/aerospace_workspace.sh" \
    --subscribe aerospace_workspace aerospace_workspace_change system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh" \
    --subscribe clock mouse.clicked

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"


sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    update_freq=60 \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change

sketchybar --add item calendar right \
    --set calendar \
    icon=󰃭 \
    icon.color=0xffeed49f \
    update_freq=1800 \
    script="$PLUGIN_DIR/calendar.sh" \
    --subscribe calendar system_woke mouse.clicked

sketchybar --add item pomodoro right \
    --set pomodoro \
    update_freq=1 \
    script="$PLUGIN_DIR/pomodoro.sh" \
    --subscribe pomodoro mouse.clicked

# source="$ITEM_DIR/music.sh"

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
sketchybar --hotload on
